### ISSUE TITLE
Where do these pictures in file_icons and resources come from ?

### ISSUE THREAD

**Issue by ClayStan** [f35f22fan/Cornus#2]
I noticed that this project is open sourced by GPL3 License, So I want to know the source of these pictures.

**Comment by f35f22fan** [comment]
Ok, so I'm using KDE Neon, so I used the (standard) mime icons from
/usr/share/icons/ - afaik they should be GPL2 or 3.

As to the (only) image from resources/ - I took some random picture I found
in google images by searching "cornelian cherries" and cropped it to a few
berries (thus heavily modifying it) - I'm no lawyer but the odds that
somebody might get offended seem none to me.

As to the Gnome dark theme - I'll reboot to another OS where I have Gnome
and see if I can reproduce the bug with the dark theme (if I have a dark
theme).
